### PR TITLE
Reworded the means section

### PR DESCRIPTION
**Pull request by ghost**
This should be easier to read.
(Also, test what kinds of events a post-merge PR triggers.)

### CODE REVIEW

**Comment by ghost** [comment]
[+Needs:Evaluation][+Needs:Merge][-Prio:High] First and third should work, second should fail.

**Comment by toolforger** [comment]
The following autolabelling commands failed:  
+Needs:Merge - not authorized

**Comment by toolforger** [comment]
The following autolabelling commands failed:
+Needs:Merge - not authorized

**Comment by ghost** [comment]
Another commit did more and better work of this.

**Pull request closed without merging**
